### ISSUE TITLE
Support of ui.service.loadBalancerIP missing

### ISSUE THREAD

**Issue by ttww** [Joxit/helm-charts#5]
If you want to use the plain MetalLB and specify the `ui.service.type=LoadBalancer` type,
you should also be able to specify an `ui.service.type=LoadBalancerIP`

Without this, the load balancer is using the first specified IP from the load balancer configuration (eg. `192.168.0.200` if the MetalLB range is `192.168.0.200-192.168.0.220` 

The generated `Service` entry should look s like

```
.........cut......cut......cut..........
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.207
  ports:
  - port: 80
.........cut......cut......cut..........
```

See your example in the docker-registry [service.yaml](https://github.com/phntom/charts/blob/4b257c804a0ea5ac899aa1bd49e334079ed4fa22/docker-registry/templates/service.yaml) template file.

I try to add it and do a pr....

**Comment by Joxit** [comment]
Hi, thank you for using my project and submitting issues :smile: 

Can you use the property `ui.service.additionalSpec` to achieve your goal ? (use the `0.4.2`, I added a fix)

```yml
ui:
  service:
    type: LoadBalancer
    additionalSpec: |
      loadBalancerIP: 192.168.0.207
```
